# Generated by Django 5.0.6 on 2024-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('number_of_seats', models.IntegerField()),
                ('description', models.TextField()),
                ('length', models.FloatField()),
                ('has_air_conditioning', models.BooleanField(default=False)),
            ],
        ),
    ]
